name: gpx
description: Package for load, manipulate, and save GPS data in GPX format (a light-weight XML data format for the interchange of GPS data - waypoints, routes, and tracks).
version: 1.1.1
homepage: https://github.com/kb0/dart-gpx/

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  quiver: '>=3.0.1'
  collection: ^1.15.0
  xml: '>=5.1.0'

dev_dependencies:
  test: ^1.6.5
